```{r}
# Cargamos librerías

library(PerformanceAnalytics)
library(zoo)
library(dplyr)

library(readxl)
library(openxlsx)
```

Toda limpieza debe realizarse en el excel

Aquí solo se correrán procesos para agilizar el proceso en excel

# Primer parcial

## Var punto extra

Primero cargamos el archivo de excel
```{r}
# Set the path to the Excel file and the sheet name
file_path <- "/Users/marcelinosanchezrodriguez/itamRepositories/adminCuantRiesgos2023Prim/varDatos.xlsx"
sheet_name <- "Sheet1"

# Read the entire sheet into a data frame
sheet <- read_excel(file_path, sheet = sheet_name)

# Print the table
head(sheet)
summary(sheet)

```

Ahora realizamos el proceso dejado de tarea para punto extra

```{r}
#agregamos fechas de predicción

sheet$fechaPred <- c(data$fechas[-1],"30-Jan-2023")

# Agregamos window size para la funcion rollapply y poder hacer lo mismo que en excel
window_size <- 252

# Definimos cuantil a cierta probabilidad
cuantilProb <- .05

##-------------------------------------------------------------------

## VAR HISTÓRICO

varHist <- rollapply(data=sheet$returns,width= window_size, FUN=VaR, p = 1-cuantilProb, method = "historical", align = "right")

#agregamos columna VaR histórico

sheet$varHist <- c(rep(NA, window_size -1), -varHist*100)



```

```{r}

##-------------------------------------------------------------------

## VAR HISTÓRICO PONDERADO

#crear serie de ponderados

nu <- 0.97
ponde <- sort(dgeom(0:(window_size-1), 1-nu)/(1-nu^252), decreasing = F)


#función para calcular ponderado

varFuncPonde <- function(vectorDatos){
    #relacionando ponderaciones

    dataFrameAux <- data.frame(rend=vectorDatos, ponde=ponde) 
    
    #reordenando por rendimiento
    
    dataFrameAux <- dataFrameAux[order(dataFrameAux$rend, decreasing = F),] 
    
    #prob acumulada

    dataFrameAux$sumaAcumPonde <- cumsum(dataFrameAux$ponde) 
    
    #filtrando para encontrar el cuantil
    
    dataFrameAux<-dataFrameAux[dataFrameAux$sumaAcumPonde>=cuantilProb,] 
    
    #sacando el cuantil

    varPonderado<-head(dataFrameAux$rend, n=1) 

    return(-varPonderado[1])
}

# Calculate VaR histórico ponderado

varHistPonde <- rollapply(data=sheet$returns,width= window_size, FUN=varFuncPonde, align = "right")

# agrega a la tabla

sheet$varHistPonde <- c(rep(NA, window_size -1), varHistPonde*100)
```


Ahora procedemos a guardarlo en excel

```{r}

# Load the existing workbook
wb <- loadWorkbook("/Users/marcelinosanchezrodriguez/itamRepositories/adminCuantRiesgos2023Prim/varDatos.xlsx")

# Add a new sheet to the workbook
addWorksheet(wb, sheetName = "NewSheet")

# Write data to the new sheet
data <- data.frame(sheet)
writeData(wb, sheet = "NewSheet", x = data)

# Save the workbook to a file
saveWorkbook(wb, "/Users/marcelinosanchezrodriguez/itamRepositories/adminCuantRiesgos2023Prim/varDatos.xlsx", overwrite = TRUE)

```

## FALTA PONER LO DEMÁS DE PUNTO extra

## Ejercicio simulación montecarlo

