
# Punto extra de Administración de riesgos


Configuramos el ambiente de trabajo
```{r}
# Cargamos librerías necesarias

library(PerformanceAnalytics)
library(zoo)
library(dplyr)

#Cargamos el archivo

data <- read.csv("file1.csv")

#Limpiamos la base

data<- data[,1:2]   #limpiamos simplemente la base

data <- data[!( is.na(data$mexbol_index)),]  #quitamos NA

#agregamos columnas de rendimiento logarítimico

data$rend <- c(NA, log(data$mexbol_index[-1] / data$mexbol_index[-length(data$mexbol_index)]))


# Eliminamos las filas de dias feriados y NA

data <- data[!(data$rend == 0 | is.na(data$rend)),]

#agregamos fechas de predicción

data$FechaPred <- c(data$fechas[-1],"30-Jan-2023")

# Agregamos window size para la funcion rollapply y poder hacer lo mismo que en excel
window_size <- 252

```


## Creamos las columnas para el cálculo de VaR histórico

```{r}

VaR_historical <- rollapply(data=data$rend,width= window_size, FUN=VaR, p = 0.95, method = "historical", align = "right")

#agregamos columna VaR histórico

data$varHist <- c(rep(NA, window_size -1), -VaR_historical*100)

```

# Calculamos VaR histórico ponderado 

```{r}
#crear serie de ponderados

nu <- 0.97
ponde <- sort(dgeom(0:251, 1-nu)/(1-nu^252), decreasing = F)

#función para calcular ponderado

varFuncPonde <- function(vectorDatos){
    dataFrameAux <- data.frame(rend=vectorDatos, ponde=ponde)
    dataFrameAux <- dataFrameAux[order(dataFrameAux$rend, decreasing = F),]
    dataFrameAux$sumaAcumPonde <- cumsum(dataFrameAux$ponde)
    dataFrameAux<-dataFrameAux[dataFrameAux$sumaAcumPonde>.05,]
    varPonderado<-head(dataFrameAux$rend, n=1)
    return(-varPonderado[1])
}

# Calculate VaR histórico ponderado

VaR_historical_ponde<- rollapply(data=data$rend,width= window_size, FUN=varFuncPonde, align = "right")

# agrega a la tabla

data$varHistPonde <- c(rep(NA, window_size -1), VaR_historical_ponde*100)

#escribe doc

write.csv(data[,c("varHist", "varHistPonde")], file = "my_data.csv")

```









