
# Examen


## Primera pregunta

```{r}
# Cargamos librerías necesarias

library(PerformanceAnalytics)
library(zoo)
library(dplyr)

#Cargamos el archivo

data <- read.csv("ejercicio1_1.csv")

# Agregamos window size para la funcion rollapply y poder hacer lo mismo que en excel
window_size <- 252

# Definimos cuantil a cierta probabilidad
cuantilProb <- .05
```


```{r}
p <- 0.95

#pregunta 11e
filtDta <- data$return
varHist <- quantile(filtDta, p, type = 1)

(espShortHist <- -mean(filtDta[filtDta< -varHist])*sqrt(22)*100)

#pregunta 11f

(espShortPar <- sd(filtDta)*dnorm(qnorm(1-p))*100*sqrt(22)/.05)
```

# problemas 12 en adelante
```{r}
data2 <-read.csv("ejercicio12_1.csv")
```



```{r}
filtDta2 <-data2$returnAritm[(278-251):278]

(varHist2 <- quantile(filtDta2, p, type = 1)*100*sqrt(10))

```



# problemas 13 
```{r}
data3 <-read.csv("ejercicio13_1.csv")
```

```{r}
filtDta3 <-data3$returnAritm[(279-251):279]

(varHist3 <- quantile(filtDta3, p, type = 1)*100*sqrt(10))

```

# problemas 14
```{r}
# 2022
data4 <-read.csv("ejercicio13_2.csv")
# 2023
data5 <-read.csv("ejercicio13_3.csv")
```

```{r}
varianSemilla <- sd(data4$returnAritm)


```